### ISSUE TITLE
Failing tests ("X is not a valid entity or mapped super class")

### ISSUE THREAD

**Issue by MidnightDesign** [Atlantic18/DoctrineExtensions#1134]
When I test the "Mapping Extension" test suite, I get the following output:

```
/usr/bin/php /tmp/ide-phpunit.php --testsuite "Mapping Extension" --configuration /DoctrineExtensions/tests/phpunit.xml.dist
Testing started at 1:18 PM ...
PHPUnit 3.7.28 by Sebastian Bergmann.

Configuration read from /DoctrineExtensions/tests/phpunit.xml.dist

Empty test suite.
Empty test suite.
Empty test suite.
Empty test suite.
Empty test suite.
Empty test suite.
Empty test suite.

Doctrine\ORM\Mapping\MappingException : Class "Tree\Fixture\Closure\CategoryClosure" sub class of "Gedmo\Tree\Entity\MappedSuperclass\AbstractClosure" is not a valid entity or mapped super class.
#0 /DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php(89): Doctrine\ORM\Mapping\MappingException::classIsNotAValidEntityOrMappedSuperClass('Tree\Fixture\Cl...')
#1 /DoctrineExtensions/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/MappingDriverChain.php(103): Doctrine\ORM\Mapping\Driver\AnnotationDriver->loadMetadataForClass('Tree\Fixture\Cl...', Object(Doctrine\ORM\Mapping\ClassMetadata))
#2 /DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(117): Doctrine\Common\Persistence\Mapping\Driver\MappingDriverChain->loadMetadataForClass('Tree\Fixture\Cl...', Object(Doctrine\ORM\Mapping\ClassMetadata))
#3 /DoctrineExtensions/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(318): Doctrine\ORM\Mapping\ClassMetadataFactory->doLoadMetadata(Object(Doctrine\ORM\Mapping\ClassMetadata), NULL, false, Array)
#4 /DoctrineExtensions/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(211): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata('Tree\Fixture\Cl...')
#5 /DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(295): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor('Tree\Fixture\Cl...')
#6 /DoctrineExtensions/lib/Gedmo/Tree/Strategy/ORM/Closure.php(81): Doctrine\ORM\EntityManager->getClassMetadata('Tree\Fixture\Cl...')
#7 /DoctrineExtensions/lib/Gedmo/Tree/TreeListener.php(261): Gedmo\Tree\Strategy\ORM\Closure->processMetadataLoad(Object(Doctrine\ORM\EntityManager), Object(Doctrine\ORM\Mapping\ClassMetadata))
#8 /DoctrineExtensions/vendor/doctrine/common/lib/Doctrine/Common/EventManager.php(59): Gedmo\Tree\TreeListener->loadClassMetadata(Object(Doctrine\ORM\Event\LoadClassMetadataEventArgs))
#9 /DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(175): Doctrine\Common\EventManager->dispatchEvent('loadClassMetada...', Object(Doctrine\ORM\Event\LoadClassMetadataEventArgs))
#10 /DoctrineExtensions/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(318): Doctrine\ORM\Mapping\ClassMetadataFactory->doLoadMetadata(Object(Doctrine\ORM\Mapping\ClassMetadata), NULL, false, Array)
#11 /DoctrineExtensions/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(211): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata('Mapping\Fixture...')
#12 /DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(295): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor('Mapping\Fixture...')
#13 /DoctrineExtensions/tests/Gedmo/Mapping/TreeMappingTest.php(65): Doctrine\ORM\EntityManager->getClassMetadata('Mapping\Fixture...')
#14 [internal function]: Gedmo\Tree\TreeMappingTest->testApcCached()
#15 /usr/share/php/PHPUnit/Framework/TestCase.php(983): ReflectionMethod->invokeArgs(Object(Gedmo\Tree\TreeMappingTest), Array)
#16 /usr/share/php/PHPUnit/Framework/TestCase.php(838): PHPUnit_Framework_TestCase->runTest()
#17 /usr/share/php/PHPUnit/Framework/TestResult.php(648): PHPUnit_Framework_TestCase->runBare()
#18 /usr/share/php/PHPUnit/Framework/TestCase.php(783): PHPUnit_Framework_TestResult->run(Object(Gedmo\Tree\TreeMappingTest))
#19 /usr/share/php/PHPUnit/Framework/TestSuite.php(775): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#20 /usr/share/php/PHPUnit/Framework/TestSuite.php(745): PHPUnit_Framework_TestSuite->runTest(Object(Gedmo\Tree\TreeMappingTest), Object(PHPUnit_Framework_TestResult))
#21 /usr/share/php/PHPUnit/Framework/TestSuite.php(705): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult), false, Array, Array, false)
#22 /usr/share/php/PHPUnit/Framework/TestSuite.php(705): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult), false, Array, Array, false)
#23 /usr/share/php/PHPUnit/TextUI/TestRunner.php(349): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult), false, Array, Array, false)
#24 /usr/share/php/PHPUnit/TextUI/Command.php(176): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#25 /tmp/ide-phpunit.php(268): PHPUnit_TextUI_Command->run(Array, true)
#26 /tmp/ide-phpunit.php(506): IDE_Base_PHPUnit_TextUI_Command::main()
#27 {main}

Doctrine\ORM\Mapping\MappingException : Class "Tree\Fixture\Closure\CategoryClosure" sub class of "Gedmo\Tree\Entity\MappedSuperclass\AbstractClosure" is not a valid entity or mapped super class.
#0 /DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php(89): Doctrine\ORM\Mapping\MappingException::classIsNotAValidEntityOrMappedSuperClass('Tree\Fixture\Cl...')
#1 /DoctrineExtensions/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/MappingDriverChain.php(103): Doctrine\ORM\Mapping\Driver\AnnotationDriver->loadMetadataForClass('Tree\Fixture\Cl...', Object(Doctrine\ORM\Mapping\ClassMetadata))
#2 /DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(117): Doctrine\Common\Persistence\Mapping\Driver\MappingDriverChain->loadMetadataForClass('Tree\Fixture\Cl...', Object(Doctrine\ORM\Mapping\ClassMetadata))
#3 /DoctrineExtensions/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(318): Doctrine\ORM\Mapping\ClassMetadataFactory->doLoadMetadata(Object(Doctrine\ORM\Mapping\ClassMetadata), NULL, false, Array)
#4 /DoctrineExtensions/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(211): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata('Tree\Fixture\Cl...')
#5 /DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(295): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor('Tree\Fixture\Cl...')
#6 /DoctrineExtensions/lib/Gedmo/Tree/Strategy/ORM/Closure.php(81): Doctrine\ORM\EntityManager->getClassMetadata('Tree\Fixture\Cl...')
#7 /DoctrineExtensions/lib/Gedmo/Tree/TreeListener.php(261): Gedmo\Tree\Strategy\ORM\Closure->processMetadataLoad(Object(Doctrine\ORM\EntityManager), Object(Doctrine\ORM\Mapping\ClassMetadata))
#8 /DoctrineExtensions/vendor/doctrine/common/lib/Doctrine/Common/EventManager.php(59): Gedmo\Tree\TreeListener->loadClassMetadata(Object(Doctrine\ORM\Event\LoadClassMetadataEventArgs))
#9 /DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(175): Doctrine\Common\EventManager->dispatchEvent('loadClassMetada...', Object(Doctrine\ORM\Event\LoadClassMetadataEventArgs))
#10 /DoctrineExtensions/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(318): Doctrine\ORM\Mapping\ClassMetadataFactory->doLoadMetadata(Object(Doctrine\ORM\Mapping\ClassMetadata), NULL, false, Array)
#11 /DoctrineExtensions/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(211): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata('Mapping\Fixture...')
#12 /DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(295): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor('Mapping\Fixture...')
#13 /DoctrineExtensions/tests/Gedmo/Mapping/TreeMappingTest.php(105): Doctrine\ORM\EntityManager->getClassMetadata('Mapping\Fixture...')
#14 [internal function]: Gedmo\Tree\TreeMappingTest->testYamlClosureMapping()
#15 /usr/share/php/PHPUnit/Framework/TestCase.php(983): ReflectionMethod->invokeArgs(Object(Gedmo\Tree\TreeMappingTest), Array)
#16 /usr/share/php/PHPUnit/Framework/TestCase.php(838): PHPUnit_Framework_TestCase->runTest()
#17 /usr/share/php/PHPUnit/Framework/TestResult.php(648): PHPUnit_Framework_TestCase->runBare()
#18 /usr/share/php/PHPUnit/Framework/TestCase.php(783): PHPUnit_Framework_TestResult->run(Object(Gedmo\Tree\TreeMappingTest))
#19 /usr/share/php/PHPUnit/Framework/TestSuite.php(775): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#20 /usr/share/php/PHPUnit/Framework/TestSuite.php(745): PHPUnit_Framework_TestSuite->runTest(Object(Gedmo\Tree\TreeMappingTest), Object(PHPUnit_Framework_TestResult))
#21 /usr/share/php/PHPUnit/Framework/TestSuite.php(705): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult), false, Array, Array, false)
#22 /usr/share/php/PHPUnit/Framework/TestSuite.php(705): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult), false, Array, Array, false)
#23 /usr/share/php/PHPUnit/TextUI/TestRunner.php(349): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult), false, Array, Array, false)
#24 /usr/share/php/PHPUnit/TextUI/Command.php(176): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#25 /tmp/ide-phpunit.php(268): PHPUnit_TextUI_Command->run(Array, true)
#26 /tmp/ide-phpunit.php(506): IDE_Base_PHPUnit_TextUI_Command::main()
#27 {main}
Empty test suite.
Empty test suite.
Empty test suite.
Empty test suite.
Empty test suite.
Empty test suite.
Empty test suite.
Empty test suite.


Time: 2.85 seconds, Memory: 27.25Mb


FAILURES!
Tests: 37, Assertions: 314, Errors: 2.

Process finished with exit code 2
```

(I've reduced the path to /DoctrineExtensions for brevity)

I tested this on several different branches, tags and commits, but I always get these two exceptions. They are thrown because the `$classAnnotations` array in `Doctrine\ORM\Mapping\Driver\AnnotationDriver::loadMetadataForClass()` is empty. But I can't figure out why.

**Comment by AkenRoberts** [comment]
Closing due to age and lack of activity. If you are interested in this issue or are still experiencing any problems described here, please add a comment!
